<?php
/**
 * SwiNOG · Venue block · server render
 *
 * Reads the venue + address + cached map URL from the queried page's
 * meta and renders the venue section. The map image itself is
 * generated by inc/venue-map.php on save_post — this block just
 * displays whatever is cached.
 *
 * @var array  $attributes
 * @var string $content
 * @var WP_Block $block
 *
 * @package SwiNOG
 */

if (!defined('ABSPATH')) {
    exit;
}

$post_id = get_queried_object_id();
if (!$post_id) {
    return '';
}

$venue   = trim((string) get_post_meta($post_id, 'swinog_event_location', true));
$address = trim((string) get_post_meta($post_id, 'swinog_event_address', true));
$map_url = (string) get_post_meta($post_id, 'swinog_event_map_url',   true);
$lat     = (string) get_post_meta($post_id, 'swinog_event_map_lat',   true);
$lng     = (string) get_post_meta($post_id, 'swinog_event_map_lng',   true);

$kicker = trim((string) ($attributes['kicker'] ?? ''));
$intro  = trim((string) ($attributes['intro']  ?? ''));

$wrapper = function_exists('get_block_wrapper_attributes')
    ? get_block_wrapper_attributes(['class' => 'swinog-venue-wrap'])
    : 'class="swinog-venue-wrap"';

$osm_link = ($lat !== '' && $lng !== '')
    ? sprintf('https://www.openstreetmap.org/?mlat=%s&mlon=%s#map=16/%s/%s', $lat, $lng, $lat, $lng)
    : '';

ob_start();
?>
<section <?php echo $wrapper; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
	<div class="swinog-venue swinog-venue--dynamic">
		<div class="swinog-venue__copy">
			<?php if ($kicker !== '') : ?>
				<div class="swinog-kicker swinog-kicker--accent"><?php echo esc_html($kicker); ?></div>
			<?php endif; ?>
			<?php if ($venue !== '') : ?>
				<h2 class="swinog-display-sm"><?php echo esc_html($venue); ?>.</h2>
			<?php endif; ?>
			<?php if ($intro !== '') : ?>
				<p class="swinog-venue__intro"><?php echo esc_html($intro); ?></p>
			<?php endif; ?>
			<?php if ($address !== '') : ?>
				<address class="swinog-venue__address"><?php echo nl2br(esc_html($address)); ?></address>
			<?php endif; ?>
			<?php if ($osm_link !== '') : ?>
				<p class="swinog-venue__osm-link">
					<a href="<?php echo esc_url($osm_link); ?>" target="_blank" rel="noopener">
						<?php esc_html_e('Open in OpenStreetMap ↗', 'swinog'); ?>
					</a>
				</p>
			<?php endif; ?>
		</div>

		<div class="swinog-venue__map">
			<?php if ($map_url !== '') : ?>
				<img
					src="<?php echo esc_url($map_url); ?>"
					alt="<?php echo esc_attr(sprintf(
						/* translators: %s = venue name or address */
						__('Map showing the location of %s', 'swinog'),
						$venue !== '' ? $venue : $address
					)); ?>"
					loading="lazy"
					decoding="async"
				/>
			<?php elseif ($address !== '' && is_user_logged_in() && current_user_can('edit_pages')) : ?>
				<div class="swinog-venue__map-placeholder">
					<p><strong><?php esc_html_e('Map not yet generated.', 'swinog'); ?></strong></p>
					<p><?php esc_html_e('Save this page again to trigger geocoding + map fetch. (Visible to editors only.)', 'swinog'); ?></p>
				</div>
			<?php endif; ?>
		</div>
	</div>
</section>
<?php

echo ob_get_clean(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
